services:
  db:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alphaai_tasks
      POSTGRES_USER: alpha
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=alpha
      - DB_PASSWORD=secret123
      - DB_NAME=alphaai_tasks
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: task-manager-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
