version: "3.9"

services:
  db:
    image: ankane/pgvector
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alphaai_tasks
      POSTGRES_USER: alpha
      POSTGRES_PASSWORD: secret123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
